---
knitr:
  opts_chunk:
    dev: svglite
format:
  typst:
    keep-typst: true
---

```{r}
source("synthesis_maximin.R")
```

# Parameters and initial setup

```{r}
lambda <- 5 # Rationality parameter
cost <- costp()
P_w <- P_wp()
P_Q <- P_Qp()
P_i <- function(i) {
  case_when(
    i %in% inters ~ 1 / 16
  )
}

Sn(1) %>%
  ggplot(aes(x = message, y = prob, fill = message)) +
  facet_grid(world ~ QuD) +
  custom_theme

```

```{r}
cost <- costp(nNPsg = 0.1, nNPpl = 0.1)
# cost <- costp()
P_w <- P_wp()
P_Q <- P_Qp(Qex = 0.005, Qml = 0.99, Qfine = 0.005)
Ln(2) %>%
  mutate(`QuD-world` = paste(QuD, world, sep = "-")) %>%
  ggplot(aes(x = `QuD-world`, y = prob, fill = `QuD-world`)) +
  facet_wrap(~ message) +
  custom_theme
```

```{r}
cost <- costp(nNPsg = 0.1, nNPpl = 0.1)
# cost <- costp()
P_w <- P_wp()
P_Q <- P_Qp(Qfine = 0.9, Qex = 0.05, Qml = 0.05)
Sn(1) %>%
  ggplot(aes(x = message, y = prob, fill = message)) +
  facet_grid(world ~ QuD) +
  custom_theme

Sn(1) %>%
  group_by(message, world) %>%
  summarise(Aggworld = sum(prob)) %>%
  group_by(world) %>%
  mutate(Aggworld = Aggworld / sum(Aggworld)) %>%
  ggplot(aes(x = message, y = Aggworld, fill = message)) +
  facet_grid(~world) +
  custom_theme
```

```{r}
cost <- costp(nNPsg = 0.1, nNPpl = 0.1)
# cost <- costp()
P_w <- P_wp()
P_Q <- P_Qp(Qfine = 0.9, Qex = 0.001, Qml = 0.009)
Sn(2) %>%
  ggplot(aes(x = message, y = prob, fill = message)) +
  facet_grid(world ~ QuD) +
  custom_theme

Sn(2) %>%
  group_by(message, world) %>%
  summarise(Aggworld = sum(prob)) %>%
  group_by(world) %>%
  mutate(Aggworld = Aggworld / sum(Aggworld)) %>%
  ggplot(aes(x = message, y = Aggworld, fill = message)) +
  facet_grid(~world) +
  custom_theme
```

# S(u\|w,Q)

```{r}
cost <- costp()
P_w <- P_wp()
# P_Q <- P_Qp(Qfine = 0.9)

# P_w <- P_wp(w0 = 0.49, w1 = 0.02, `w2+` = 0.35)
# P_Q <- P_Qp(Qex = 0.96, Qml = 0.02, Qfine = 0.02)
Sn(1) %>%
  ggplot(aes(x = message, y = prob, fill = message)) +
  facet_grid(world ~ QuD) +
  custom_theme

```

# L(w,Q\|u)

```{r}
Ln(1) %>%
  mutate(`QuD-world` = paste(QuD, world, sep = "-")) %>%
  ggplot(aes(x = `QuD-world`, y = prob, fill = `QuD-world`)) +
  facet_wrap(~ message) +
  custom_theme
```

# L(Q\|u)

```{r}
Ln(1) %>%
  group_by(message, QuD) %>%
  summarise(AggQuD = sum(prob)) %>%
  group_by(message) %>%
  mutate(AggQuD = AggQuD / sum(AggQuD)) %>%
  ggplot(aes(x = QuD, y = AggQuD, fill = QuD)) +
  facet_wrap(~message) +
  custom_theme
```

# L(w\|u)

```{r}
Ln(1) %>%
  group_by(message, world) %>%
  summarise(Aggworld = sum(prob)) %>%
  group_by(message) %>%
  mutate(Aggworld = Aggworld / sum(Aggworld)) %>%
  ggplot(aes(x = world, y = Aggworld, fill = world)) +
  facet_wrap(~message) +
  custom_theme
```

# S(u\|w)

```{r}
Sn(1) %>%
  group_by(message, world) %>%
  summarise(Aggworld = sum(prob)) %>%
  group_by(world) %>%
  mutate(Aggworld = Aggworld / sum(Aggworld)) %>%
  ggplot(aes(x = message, y = Aggworld, fill = message)) +
  facet_grid(~world) +
  custom_theme
```